print(head(cars))
cat("\n")
print(head(mtcars))
cat("\n")
print("Summary of mtCars datset")
print(summary(mtcars))
print("Summary statistics for Cars")
print(summary(cars))
print("Structure of cars dataset")
print(str(cars))
print("Structure of mtcars dataset")
print(str(mtcars))
#_________________________
cat("\n")
print("Quartiles for mtcars dataset")
print(quantile(mtcars$mpg,probs = c(0,0.25,0.5,0.75,1)))
cat("\n")
print("Quartiles for cars dataset")
print(quantile(cars$speed,probs = c(0,0.25,0.5,0.75,1)))